### ISSUE TITLE
generator.rb:75 no implicit conversion of nil into String

### ISSUE THREAD

**Issue by RobMcA** [captn3m0/jekyll-sqlite#5]
I'm new to Jekyll and Ruby, so I hope this is just something obvious I've missed. I get the following error when trying to start the server with sqlite_jekyll installed.

```
/Users/rmcarthu/.gem/ruby/3.3.5/gems/jekyll-sqlite-0.1.5/lib/jekyll-sqlite/generator.rb:75:in `exist?': no implicit conversion of nil into String (TypeError)

      return false unless File.exist?(config["file"])
                                      ^^^^^^^^^^^^^^
```

This seems to mean `sqlite[*].file` is not being read properly from `_config.yml`. The northwind demo project works fine. I've tried copying the _config.yml from that project and it gets the same error. 

How to recreate:

- create a new project with `jekyll new mytest`
- cd mytest
- In Gemfile add:

```
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sqlite", "~> 0.1.5"
end
```
- In _config.xml add:
```
plugins:
  - jekyll-feed
  - jekyll_sqlite

sqlite:
  - data: customers
    file: *db
    query: SELECT * from Customers
```
- Add `northwind.db` to `_db`
- Run `bundle install`
- Run `bundle exec jekyll serve`

Result
```
/Users/rmcarthu/.gem/ruby/3.3.5/gems/jekyll-sqlite-0.1.5/lib/jekyll-sqlite/generator.rb:75:in `exist?': no implicit conversion of nil into String (TypeError)

      return false unless File.exist?(config["file"])
                                      ^^^^^^^^^^^^^^
	from /Users/rmcarthu/.gem/ruby/3.3.5/gems/jekyll-sqlite-0.1.5/lib/jekyll-sqlite/generator.rb:75:in `validate_config'
	from /Users/rmcarthu/.gem/ruby/3.3.5/gems/jekyll-sqlite-0.1.5/lib/jekyll-sqlite/generator.rb:125:in `block in gen'
	from /Users/rmcarthu/.gem/ruby/3.3.5/gems/jekyll-sqlite-0.1.5/lib/jekyll-sqlite/generator.rb:124:in `each'
	from /Users/rmcarthu/.gem/ruby/3.3.5/gems/jekyll-sqlite-0.1.5/lib/jekyll-sqlite/generator.rb:124:in `gen'
	from /Users/rmcarthu/.gem/ruby/3.3.5/gems/jekyll-sqlite-0.1.5/lib/jekyll-sqlite/generator.rb:136:in `generate'
```

**Comment by captn3m0** [comment]
So `file` is supposed to point at your sqlite file itself. The `*db` syntax is a special anchoring thing in YAML, which I use to avoid repeating the same filename across queries.

Just setting `file: db.db` (with your filename) should fix this.

**Comment by RobMcA** [comment]
Thanks for the reply. I had tried the database name instead and while I didn't get an error, I had no SQLite messages in the console, and no data in my pages.

Having ruled out the error reported above thanks to your response, I dug into things a bit deeper and it looks like the underlying related to `github-pages v.232`. The plugin never seems to intitialize but if I switch to Jeykyll 4.3.3 instead everything works fine. 

Thanks for your help.

**Comment by captn3m0** [comment]
Maybe relevant: the GitHub Pages gem runs in safe mode by default, and this plugin might not initialize under that.
